// <auto-generated />
namespace IPSAInventario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class modifyTriggersTGR_DEL_PERIFERICOSTGR_DEL_COMPUTADORATGR_DEL_SOFTWAREaddNewOnes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifyTriggersTGR_DEL_PERIFERICOSTGR_DEL_COMPUTADORATGR_DEL_SOFTWAREaddNewOnes));
        
        string IMigrationMetadata.Id
        {
            get { return "202208171710139_modifyTriggersTGR_DEL_PERIFERICOS-TGR_DEL_COMPUTADORA-TGR_DEL_SOFTWARE-addNewOnes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
