// <auto-generated />
namespace IPSAInventario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class modifyTGR_DEL_COMPUTADORAandTGR_UPD_COMPUTADORA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifyTGR_DEL_COMPUTADORAandTGR_UPD_COMPUTADORA));
        
        string IMigrationMetadata.Id
        {
            get { return "202208091850091_modifyTGR_DEL_COMPUTADORAandTGR_UPD_COMPUTADORA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
